Check for git merge conflict artifacts before commit

diff --git a/git_template/hooks/pre-commit b/git_template/hooks/pre-commit
--- a/git_template/hooks/pre-commit
+++ b/git_template/hooks/pre-commit
@@ -106,6 +106,16 @@ for FILE in $CHANGED_FILES; do
     continue
   fi
 
+  # Check for merge conflict artifacts in the file
+  merge_conflict_output=$(echo $FILE | xargs egrep '[><]{7}' -H -I --line-number)
+
+  ## If the egrep command has any hits - echo a warning and exit with non-zero status.
+  if [ $? == 0 ]
+  then
+      errors+=("WARNING: Possible git merge conflict artifacts in: $FILE")
+      errors+=($merge_conflict_output)
+  fi
+
   case "$resource" in
     *.php)
       if ! check_php_syntax $resource; then
