Skip git hash checking on empty repo to reduce error output in the git first commit

diff --git a/git_template/hooks/prepare-commit-msg b/git_template/hooks/prepare-commit-msg
--- a/git_template/hooks/prepare-commit-msg
+++ b/git_template/hooks/prepare-commit-msg
@@ -43,20 +43,25 @@ fi
 # If aspell is installed spell check all my commits
 if [ -z "$SKIP_CUSTOM_CHECKS" ] && command_exists aspell; then
 
-  # Get commit message, Don't spellcheck Singed-off-by messages
-  MESSAGE=$(cat $1 | grep -v "^Signed-off-by:")
+    # Get commit message, Don't spellcheck Singed-off-by messages
+    MESSAGE=$(cat $1 | grep -v "^Signed-off-by:")
 
-  # aspell has no idea of git hashes so remove them from spellchecking
-  HASHES=$(git rev-list --all)
-  while read -r line; do
-      MESSAGE=$(echo $MESSAGE | sed "s/$line//g")
-  done <<< "$HASHES"
+    # Check if this is empty repo
+    # If its not empty repo remove all git HASH messages
+    git --no-pager log --decorate=short --pretty=oneline -n1 2>&1 >/dev/null | grep 'does not have any commits yet' > /dev/null
+    if [ $? != 0 ]
+    then
+        # aspell has no idea of git hashes so remove them from spellchecking
+        HASHES=$(git rev-list --all)
+        while read -r line; do
+            MESSAGE=$(echo $MESSAGE | sed "s/$line//g")
+        done <<< "$HASHES"
+    fi
 
   # Spell check commit message
-  echo $MESSAGE
   TYPOS=$(echo $MESSAGE | aspell list -d en_US)
   if [ -n "$TYPOS" ]; then
-    echo -e "ERROR: spell check failed on words: \n$TYPOS"
+    echo "ERROR: spell check failed on words: \n$TYPOS"
     echo "Edit ~/.aspell.en.pws to accept more words"
     echo "Skip this: $ run-it-please"
     exit 1
